import { Schema } from 'effect';
import type { Brand } from 'effect/Brand';
import { VariantSchema } from 'effect/unstable/schema';

// TODO: Keep an eye on the progress of Effect v4 Models as they intend to be more agnostic to the database and more flexible.
// Everything below are ports of Model from @effect/sql to prevent issues with types being out of sync.

export const {
  Class,
  Field,
  FieldExcept,
  FieldOnly,
  Struct,
  Union,
  extract,
  fieldEvolve,
} = VariantSchema.make({
  variants: ['get', 'add', 'update', 'json', 'jsonAdd', 'jsonUpdate'],
  defaultVariant: 'get',
});

export type Any = Schema.Top & {
  readonly fields: Schema.Struct.Fields;
  readonly add: Schema.Top;
  readonly update: Schema.Top;
  readonly json: Schema.Top;
  readonly jsonAdd: Schema.Top;
  readonly jsonUpdate: Schema.Top;
};

export type AnyNoContext = Schema.Top & {
  readonly fields: Schema.Struct.Fields;
  readonly add: Schema.Top;
  readonly update: Schema.Top;
  readonly json: Schema.Top;
  readonly jsonAdd: Schema.Top;
  readonly jsonUpdate: Schema.Top;
};

export type VariantsDatabase = 'get' | 'add' | 'update';
export type VariantsJson = 'json' | 'jsonAdd' | 'jsonUpdate';

export const fields: <A extends VariantSchema.Struct<any>>(
  self: A
) => A[typeof VariantSchema.TypeId] = VariantSchema.fields;
export const Override: <A>(value: A) => A & Brand<'Override'> =
  VariantSchema.Override;

export type Generated<S extends Schema.Top> = VariantSchema.Field<{
  readonly get: S;
  readonly update: S;
  readonly json: S;
}>;

/**
 * A field that represents a column that is generated by the database.
 *
 * It is available for selection and update, but not for insertion.
 */
export const Generated = <S extends Schema.Top>(schema: S): Generated<S> =>
  Field({
    get: schema,
    update: schema,
    json: schema,
  });

export type GeneratedByApp<S extends Schema.Top> = VariantSchema.Field<{
  readonly get: S;
  readonly add: S;
  readonly update: S;
  readonly json: S;
}>;

/**
 * A field that represents a column that is generated by the application.
 *
 * It is required by the database, but not by the JSON variants.
 */
export const GeneratedByApp = <S extends Schema.Top>(
  schema: S
): GeneratedByApp<S> =>
  Field({
    get: schema,
    add: schema,
    update: schema,
    json: schema,
  });

export type Sensitive<S extends Schema.Top> = VariantSchema.Field<{
  readonly get: S;
  readonly add: S;
  readonly update: S;
}>;

/**
 * A field that represents a sensitive value that should not be exposed in the
 * JSON variants.
 */
export const Sensitive = <S extends Schema.Top>(schema: S): Sensitive<S> =>
  Field({
    get: schema,
    add: schema,
    update: schema,
  });
