/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FunctionsRouteImport } from './routes/functions'
import { Route as FirestoreRouteImport } from './routes/firestore'
import { Route as IndexRouteImport } from './routes/index'

const FunctionsRoute = FunctionsRouteImport.update({
  id: '/functions',
  path: '/functions',
  getParentRoute: () => rootRouteImport,
} as any)
const FirestoreRoute = FirestoreRouteImport.update({
  id: '/firestore',
  path: '/firestore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/firestore': typeof FirestoreRoute
  '/functions': typeof FunctionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/firestore': typeof FirestoreRoute
  '/functions': typeof FunctionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/firestore': typeof FirestoreRoute
  '/functions': typeof FunctionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/firestore' | '/functions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/firestore' | '/functions'
  id: '__root__' | '/' | '/firestore' | '/functions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FirestoreRoute: typeof FirestoreRoute
  FunctionsRoute: typeof FunctionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/functions': {
      id: '/functions'
      path: '/functions'
      fullPath: '/functions'
      preLoaderRoute: typeof FunctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firestore': {
      id: '/firestore'
      path: '/firestore'
      fullPath: '/firestore'
      preLoaderRoute: typeof FirestoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FirestoreRoute: FirestoreRoute,
  FunctionsRoute: FunctionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
